import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

import logo from "../public/logo.png";
import con from "../public/con.jpg";
import sakura from "../public/sakura.png";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="header-contents">
          <h1>
            <Image src={logo} alt="SlugCon 2022" />
          </h1>
          <h2>
            🕐 May 14th, 1-7PM
            <br />
            📍 C9/Lewis MPR{" "}
          </h2>
          <div className="nav">
            <button>Livestream</button>
            <button>Artist Showcase</button>
            <button>Schedule</button>
          </div>
          {/* <div className="header-decor">
            <Image alt="sakura blossoms" src={sakura}></Image>
          </div> */}
        </div>
      </header>

      <main>
        <div className="row">
          <div className="textCol">
            <h2>UCSC’s very own anime and gaming convention!</h2>
            <h3>Admission is free!</h3>
            <p>
              SlugCon is UCSC's very own anime and gaming convention, hosted by
              SAMA, Slug Gaming, and GDA.
            </p>
            <p>
              Join us at the College Nine/Lewis MPR on May 14th for our Artists’
              Alley, panels, giveaways, and more!
            </p>
          </div>
          <div className="imgCol">
            <Image className="imgCol" src={con} alt="SlugCon 2022" />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
